apiVersion: apps/v1
kind: Deployment
metadata:
  name: minefight-api
  namespace: minecraft
spec:
  selector:
    matchLabels:
      app: minefight-api
  template:
    metadata:
      labels:
        app: minefight-api
    spec:
      serviceAccountName: minefight-api
      containers:
        - name: minefight-api
          image: minefight/web-api:latest
          env:
            - name: ORCHESTRATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - configMapRef:
                name: minefight-api-config-env
            - secretRef:
                name: minefight-api-secret-env
          resources:
            limits:
              memory: "1G"
              cpu: "250m"
          ports:
            - containerPort: 3000
