apiVersion: v1
kind: Service
metadata:
  name: mfmc-servers
  namespace: minecraft
spec:
  selector:
    app: minefight
    minefight.fr/api-managed: "true"
  ports:
  - port: 25565
    targetPort: 25565
